imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: "%debug_toolbar%"
    intercept_redirects: "%debug_redirects%"

monolog:
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        console:
            type:   console
            bubble: false
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

assetic:
    use_controller: "%use_assetic_controller%"

#Vich Uploader Configuration
vich_uploader:
    db_driver: orm
    mappings:
        game_image:
            uri_prefix:         /symfony/web/uploads/images/game
            upload_destination: %kernel.root_dir%/../web/uploads/images/game
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true

#swiftmailer:
#    delivery_address: me@example.com
