yapspeedrun_index:
    path: /
    defaults: { _controller: YapSpeedrunBundle:Speedrun:index }

yapspeedrun_howto:
    path: /howto
    defaults: { _controller: YapSpeedrunBundle:Speedrun:howTo }

yapspeedrun_addgame:
    path: /game/add
    defaults: { _controller: YapSpeedrunBundle:Speedrun:addGame }

yapspeedrun_editgame:
    path: /game/{slug}/edit
    defaults: { _controller: YapSpeedrunBundle:Speedrun:editGame }

yapspeedrun_seegame:
    path: /game/{slug}
    defaults: { _controller: YapSpeedrunBundle:Speedrun:seeGame }

yapspeedrun_seelevel:
    path: /game/{slug}/{levelSlug}
    defaults: { _controller: YapSpeedrunBundle:Speedrun:seeLevel }

yapspeedrun_latesttimes:
    path: /times
    defaults: { _controller: YapSpeedrunBundle:Speedrun:latestTimes }

yapspeedrun_watch:
    path: /game/{slug}/watch/{video}
    defaults: { _controller: YapSpeedrunBundle:Speedrun:watch }

yapspeedrun_validategame:
    path: /validate/game/{slug}
    defaults: { _controller: YapSpeedrunBundle:Speedrun:validateGame }
    options:
        expose: true

yapspeedrun_addmodo:
    path: /game/{slug}/addModo/{user}
    defaults: { _controller: YapSpeedrunBundle:Speedrun:addModo, user: null }

yapspeedrun_listgames:
    path: /games
    defaults: { _controller: YapSpeedrunBundle:Speedrun:listGames }

yapspeedrun_validatelistgames:
    path: /validate/games
    defaults: { _controller: YapSpeedrunBundle:Speedrun:validateListGames }

yapspeedrun_addcategory:
    path: /category/add
    defaults: { _controller: YapSpeedrunBundle:Speedrun:addCategory }

yapspeedrun_addplatform:
    path: /platform/add
    defaults: { _controller: YapSpeedrunBundle:Speedrun:addPlatform }

yapspeedrun_submittime:
    path: /game/{slug}/submit/time
    defaults: { _controller: YapSpeedrunBundle:Speedrun:submitTime }

yapspeedrun_createlinker:
    path: /game/{slug}/create/runtype
    defaults: { _controller: YapSpeedrunBundle:Speedrun:createLinker }

yapspeedrun_levelgraph:
    path: /game/{slug}/{level}/graph/{linker}-{levelId}
    defaults: { _controller: YapSpeedrunBundle:Speedrun:levelGraph }
    requirements:
        level: '[a-zA-Z0-9-_\/.]+'

yapspeedrun_seeprofile:
    path: /profile/{username}
    defaults: { _controller: YapSpeedrunBundle:Speedrun:seeProfile }

_difficultyByGameId:
    path: /listByGame
    defaults: { _controller: YapSpeedrunBundle:Speedrun:getByGameId }

_addTime:
    path: /addTime
    defaults: { _controller: YapSpeedrunBundle:Speedrun:addTime }
    options:
        expose: true

_subscriptionManager:
    path: /subscribeManager/{slug}
    defaults: { _controller: YapSpeedrunBundle:Speedrun:subscriptionManager }
    options:
        expose: true

_subscribe:
    path: /subscribe/{slug}
    defaults: { _controller: YapSpeedrunBundle:Speedrun:subscribe }
    options:
        expose: true

_unsubscribe:
    path: /unsubscribe/{slug}
    defaults: { _controller: YapSpeedrunBundle:Speedrun:unsubscribe }
    options:
        expose: true