parameters:
#    yap_speedrun.example.class: Yap\SpeedrunBundle\Example

services:
    yap.twig.yap_extension:
        class: Yap\SpeedrunBundle\Twig\SpeedrunExtension
        tags:
            - { name: twig.extension }
    yap_speedrun.ranktester:
        class: Yap\SpeedrunBundle\Ranktester\YapRanktester
    yap_speedrun.videoresolver:
        class: Yap\SpeedrunBundle\Videoresolver\YapVideoresolver
#    yap_speedrun.example:
#        class: %yap_speedrun.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
