<?php

namespace Yap\SpeedrunBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Yap\SpeedrunBundle\Entity\Linker;

/**
 * LinkerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkerRepository extends EntityRepository
{
	public function linkerExist(Linker $linker)
	{
    	$qb = $this->_em->createQueryBuilder();
		
		$qb->select('l')
			->from('YapSpeedrunBundle:Linker', 'l')
			->where('l.game = :game')
			->setParameter('game', $linker->getGame())
			
			->andWhere('l.difficulty = :difficulty')
			->setParameter('difficulty', $linker->getDifficulty())
			
			->andWhere('l.scripted = :scripted')
			->setParameter('scripted', $linker->getScripted())
			
			->andWhere('l.segmented = :segmented')
			->setParameter('segmented', $linker->getSegmented())
			
			->andWhere('l.tas = :tas')
			->setParameter('tas', $linker->getTas())
			
			->andWhere('l.version = :version')
			->setParameter('version', $linker->getVersion())
			
			->andWhere('l.category = :category')
			->setParameter('category', $linker->getCategory());

    return $qb->getQuery()->getOneOrNullResult();
	}
}
