<?php

namespace Yap\SpeedrunBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Yap\SpeedrunBundle\Entity\Rating;

/**
 * RatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingRepository extends EntityRepository
{
	public function isGameValid($rating)
	{
    	$qb = $this->_em->createQueryBuilder();
		
		$qb->select('r')
			->from('YapSpeedrunBundle:rating', 'r')
			->where('r.id = :id')
			->setParameter('id', $rating);

    return $qb->getQuery()->getOneOrNullResult();
	}
}
