<?php

namespace Yap\SpeedrunBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeRepository extends EntityRepository
{
	public function addTime($linker_id, $level_id, $user_id, $time, $video, $note)
	{
		$qb = $this->_em->createQueryBuilder();
		$qb
		    ->insert('spr_time')
		    ->setValue('linker_id', '?')
		    ->setValue('level_id', '?')
		    ->setValue('user_id', '?')
		    ->setValue('time', '?')
		    ->setValue('video', '?')
		    ->setValue('note', '?')
		    ->setParameter(0, $linker_id)
		    ->setParameter(1, $level_id)
		    ->setParameter(2, $user_id)
		    ->setParameter(3, $time)
		    ->setParameter(4, $video)
		    ->setParameter(5, $note)
		;
	}

	public function getBestTimes($linker)
	{
		$qb = $this->_em->createQueryBuilder();
		
		$qb->select('t')
			->from('YapSpeedrunBundle:Time', 't')
			->where('t.linker = :linker')
			->setParameter('linker', $linker)
			->add('orderBy', 't.time ASC');

		return $qb->getQuery()->getResult();
	}

	public function getOldTime($linker, $level, $user)
	{
		$qb = $this->_em->createQueryBuilder();
		
		$qb->select('t')
			->from('YapSpeedrunBundle:Time', 't')
			->where('t.linker = :linker')
			->setParameter('linker', $linker)
			
			->andWhere('t.level = :level')
			->setParameter('level', $level)

			->andWhere('t.user = :user')
			->setParameter('user', $user)

			->andWhere('t.pb = :pb')
			->setParameter('pb', 1)
			
			->setMaxResults(1);

		return $qb->getQuery()->getOneOrNullResult();
	}

	public function getOldWrTime($linker, $level)
	{
		$qb = $this->_em->createQueryBuilder();
		
		$qb->select('t')
			->from('YapSpeedrunBundle:Time', 't')
			->where('t.linker = :linker')
			->setParameter('linker', $linker)
			
			->andWhere('t.level = :level')
			->setParameter('level', $level)

			->andWhere('t.wr = :wr')
			->setParameter('wr', 1)

			->setMaxResults(1);

		return $qb->getQuery()->getOneOrNullResult();
	}

	public function getCatWr($linker)
	{
		$qb = $this->_em->createQueryBuilder();
		
		$qb->select('t')
			->from('YapSpeedrunBundle:Time', 't')
			->where('t.linker = :linker')
			->setParameter('linker', $linker)

			->andWhere('t.wr = :wr')
			->setParameter('wr', 1)

			->add('orderBy', 't.level ASC');

		return $qb->getQuery()->getResult();
	}

	public function getLevelTime($linker, $level)
	{
		$qb = $this->_em->createQueryBuilder();
		
		$qb->select('t')
			->from('YapSpeedrunBundle:Time', 't')
			->where('t.linker = :linker')
			->setParameter('linker', $linker)

			->andWhere('t.level = :level')
			->setParameter('level', $level)

			->add('orderBy', 't.time DESC');

		return $qb->getQuery()->getResult();
	}

	public function getLevelOldWrTime($linker, $level)
	{
		$qb = $this->_em->createQueryBuilder();
		
		$qb->select('t')
			->from('YapSpeedrunBundle:Time', 't')
			->where('t.linker = :linker')
			->setParameter('linker', $linker)

			->andWhere('t.level = :level')
			->setParameter('level', $level)

			->andWhere('t.oldwr = 1')

			->add('orderBy', 't.time DESC');

		return $qb->getQuery()->getResult();
	}
}
